services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
    - "80:80"
    - "443:443"
    secrets:
      - ssl_certificate.crt
      - ssl_private.key
    
secrets:
  ssl_certificate.crt:
    file: ./ssl/nginx.crt
  ssl_private.key:
    file: ./ssl/nginx.key